[breakout]
lookback_period = 20  # Lookback period for calculating resistance/support
volatility_threshold = 0.05  # Minimum volatility to consider a breakout
volume_multiplier = 2.0  # Volume must be 2x the average to confirm breakout
stop_loss = 0.02  # 2% stop-loss
take_profit = 0.10  # 10% take-profit
