[ensemble]
base_weights = { "MACD" = 0.4, "RSI" = 0.3, "Breakout" = 0.3 }
performance_window = 24  # Evaluate performance over 24 hours
confidence_threshold = 0.6  # Require 60% confidence to act
stop_loss = 0.02  # Global 2% stop-loss
take_profit = 0.10  # Global 10% take-profit
